---
- name: Install various shells
  hosts: localhost
  become: yes
  vars:
    shells:
      - csh
      - tcsh
      - bash
      - ksh
      - zsh

  tasks:
    - name: Ensure shells are installed
      package:
        name: "{{ shells }}"
        state: present

  # post_tasks:
    # - name: Set the default shell for the current user (optional)
      # lineinfile:
        # path: /etc/passwd
        # regexp: '^{{ ansible_user }}:'
        # line: '{{ ansible_user }}:x:{{ ansible_uid }}:{{ ansible_gid }}:/home/{{ ansible_user }}:/bin/zsh'
        # state: present
    # 
    # - name: Ensure zsh is installed as the default shell for root (optional)
      # lineinfile:
        # path: /etc/passwd
        # regexp: '^root:'
        # line: 'root:x:0:0:root:/root:/bin/zsh'
        # state: present

