---
- name: Install and compile SLURM
  hosts: all
  become: yes
  vars:
    slurm_version: "21.08"  # Change this to the desired version if needed

  tasks:
    - name: Ensure git is installed
      package:
        name: git
        state: present

    - name: Clone SLURM repository
      git:
        repo: https://github.com/SchedMD/slurm.git
        dest: /tmp/slurm-source
        version: "v{{ slurm_version }}"

    - name: Change directory to the cloned source code
      command: cd /tmp/slurm-source

    - name: Bootstrap the SLURM build
      command: ./autogen.sh
      args:
        chdir: /tmp/slurm-source

    - name: Configure the SLURM build
      command: ./configure --prefix=/usr/local/slurm
      args:
        chdir: /tmp/slurm-source

    - name: Compile SLURM
      command: make -j $(nproc)
      args:
        chdir: /tmp/slurm-source

    - name: Install SLURM
      command: make install
      args:
        chdir: /tmp/slurm-source

    - name: Clean up the source directory
      file:
        path: /tmp/slurm-source
        state: absent

  post_tasks:
    - name: Ensure SLURM is started
      service:
        name: slurmctld
        state: started
        enabled: yes

    # XXX this is running on the head node?
    # should this operate on the WW chroot dir for the nodes?
    # - name: Ensure slurmd is started on compute nodes
    #   service:
    #     name: slurmd
    #     state: started
    #     enabled: yes

